baseURL = "http://nadeus.com/"
languageCode = "fr-FR"
title = "Nadeus"
theme = "hugo-tania"
params:
  titleEmoji: '😎'
  socialOptions:
    github: 
    twitter: 

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true