baseURL: "http://nadeus.com/"
languageCode: "fr-FR"
title: "Nadeus"
theme: "hugo-tania"
params:
  titleEmoji: '🦓'


menu:
  header:
    - name: Ressources
      url: "/ressources/"
      weight: 10
    - name: Articles
      url: "/articles/"
      weight: 20

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true